import { useNavigate, useParams } from 'react-router-dom'
import { Button, EmptyState, Screen, StatTile } from '../../components/ui'
import { BarList, Figure } from '../../components/charts'
import { Icon } from '../../components/icons'
import { useExecutiveMetrics, useReport, useThemes } from '../../store/hooks'
import { fmtDate, fmtNum, fmtUSD } from '../../lib/format'

export function ReportView() {
  const { id } = useParams()
  const report = useReport(id)
  const navigate = useNavigate()
  const m = useExecutiveMetrics()
  const themes = useThemes({ sort: 'impact' })

  if (!report) {
    return (
      <Screen>
        <EmptyState icon="file-text" title="Report not found" action={<Button onClick={() => navigate('/reports')}>Back to reports</Button>} />
      </Screen>
    )
  }

  if (report.status === 'generating') {
    return (
      <Screen width="max-w-3xl">
        <div className="flex flex-col items-center py-24 text-center">
          <span className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-rust-wash text-rust">
            <Icon name="sparkles" size={22} />
          </span>
          <div className="font-display text-heading text-ink">This report is still generating…</div>
          <Button className="mt-4" variant="secondary" onClick={() => navigate('/reports/generating?id=' + report.id)}>
            Watch it build
          </Button>
        </div>
      </Screen>
    )
  }

  return (
    <Screen width="max-w-3xl">
      <div className="mb-4 flex items-center justify-between">
        <button onClick={() => navigate('/reports')} className="inline-flex items-center gap-1.5 text-sm text-ink-mute hover:text-rust">
          <Icon name="chevron-right" size={14} className="rotate-180" /> Reports
        </button>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="secondary" icon="share" onClick={() => navigate(`/reports/${report.id}/share`)}>Share</Button>
          <Button size="sm" variant="secondary" icon="download">Export</Button>
        </div>
      </div>

      <div className="text-xs font-semibold uppercase tracking-wider text-rust mb-2">{report.audience} report</div>
      <h1 className="font-display text-display leading-tight text-ink">{report.title}</h1>
      <div className="mt-2 text-sm text-ink-mute">{report.period} · generated by {report.createdBy} · {fmtDate(report.createdISO)}</div>

      {/* KPI strip */}
      <div className="mt-6 grid grid-cols-2 gap-3 border-y border-line py-5 sm:grid-cols-4">
        <StatTile label="Insights" value={fmtNum(m.total)} />
        <StatTile label="Positive" value={`${m.posPct}%`} />
        <StatTile label="ARR at risk" value={fmtUSD(m.arrAtRisk)} />
        <StatTile label="NPS proxy" value={m.npsProxy} />
      </div>

      {/* sections */}
      <div className="mt-8 flex flex-col gap-8">
        {report.sections.map((s) => (
          <section key={s.id}>
            <h2 className="font-display text-heading text-ink">{s.heading}</h2>
            <p className="mt-2 leading-relaxed text-ink-soft">{s.body}</p>
            {s.kind === 'themes' && (
              <div className="mt-4">
                <Figure title="Top themes by impact">
                  <BarList items={themes.slice(0, 5).map((t) => ({ label: t.title, value: t.impact, display: `${t.impact}`, to: `/themes/${t.id}` }))} max={100} />
                </Figure>
              </div>
            )}
          </section>
        ))}
      </div>

      {report.sharedWith.length > 0 && (
        <div className="mt-10 border-t border-line pt-4 text-sm text-ink-mute">
          Shared with {report.sharedWith.join(', ')}.
        </div>
      )}
    </Screen>
  )
}
